<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var AddressView $addressView */
/** @var Escaper $escaper */

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\AddressView;

$addressView = $viewModels->require(AddressView\AddressViewBilling::class);
?>
<div>
    <?= /* @noEscape */ $addressView->renderView() ?>
</div>
